config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  namespace :admin do 
    resources :users
  end

  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user
  validate  :set_nameless_name
  validates :name, presence: true, length: { maximum: 30 }
  
  default_scope { order(created_at: :desc) }

  has_one_attached :image

  def self.csv_attributes 
    [:name, :description, :created_at, :updated_at]
  end

  def self.generate_csv
    CSV.generate(headers: true) do |csv|
      csv << csv_attributes
      all.each do |task|
        csv << csv_attributes.map { |attr| task.send(attr) }
      end
    end
  end

  private 

  def set_nameless_name
    self.name = '沒有該用戶' if name.nil?
  end


  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :tasks
  # has_secure_password 會自動附帶3個驗證：
  #檢查密碼是否存在, 密碼長度必須是不是大於 72 bytes, 確認密碼填寫是否正確 (using a XXX_confirmation attribute)
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index 
    @users = User.all
  end

  def new 
    @user = User.new
  end

  def create 
    @user = User.new(set_user_params)

    if @user.save
      redirect_to admin_users_path, notice: "用戶「#{@user.name}」已成功新增。"
    else
      render :new
    end
  end
  
  def show; end

  def edit; end

  def update 
    if @user.update(set_user_params)
      redirect_to admin_users_path, notice: "用戶「#{@user.name}」已被編輯。"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, alert: "用戶「#{@user.name} 已被刪除。" 
    end
  end

  private

  def set_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required
  
  private 

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new; end

  def create 
    user = User.find_by(email: session_user_params[:email])
    # @user&.authenticate() == @user && @user.authenticate()
    if user&.authenticate(session_user_params[:password])
      session[:user_id] = user.id
      redirect_to '/', notice: '您已成功登入。'
    else
      render :new
    end
  end

  def destroy
    # Resets the session by clearing out all the objects stored within and initializing a new session object.
    reset_session

    redirect_to '/', alert: '您已登出。'
  end

  private

  def session_user_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page]).per(10)

    respond_to do |format|
      format.html
      format.csv {
        send_data(@tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" )
      }
    end
  end

  def new 
    @task = Task.new
  end

  def create 
    @task = current_user.tasks.new(set_task_params)

    if @task.save 
      Rails.logger.info "tasks: #{@task.attributes.inspect}"
      redirect_to task_path(@task), notice: "已新增任務「#{@task.name}」。"
    else
      render :new
    end
  end

  def show ;end

  def edit ;end

  def update 

    if @task.update(set_task_params)
      redirect_to task_path(@task), notice: "已更新任務「#{@task.name}」。"
    else
      render :edit
    end
  end

  def destroy

    @task.destroy
    redirect_to tasks_path, notice: "已刪除任務「#{@task.name}」。"
  end

  private 

  def set_task_params
    params.require(:task).permit(:name, :description, :image)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.haml
= form_with model: [:admin, @user], local: true do |f|
  .form-group
    = f.label :name, '用戶名稱'
    = f.text_field :name, class: 'form-control', style: 'width: auto;'
  .form-group
    = f.label :email, 'Email'
    = f.text_field :email, class: 'form-control', style: 'width: auto;'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理員
  .form-group
    = f.label :password, '密碼'
    = f.password_field :password, class: 'form-control', style: 'width: auto;'
  .form-group
    = f.label :password_confirmation, '密碼（確認）'
    = f.password_field :password_confirmation, class: 'form-control', style: 'width: auto;'
  %br 
  %br
  = f.submit nil, class: 'btn btn-primary'  

app/views/admin/users/edit.html.haml
%h1 編輯用戶
.nav.justify-content-end
  = link_to('用戶列表', admin_users_path, class: 'nav-link')

= render partial: 'form', locals: { task: @user }

app/views/admin/users/index.html.haml
%h1 用戶列表

= link_to('新增用戶', new_admin_user_path, class: 'btn btn-primary')

.mb-3 
%table.table.table-hover
  %thread.thread-default
    %tr
      %th= User.human_attribute_name(:name)
      %th= User.human_attribute_name(:email)
      %th= User.human_attribute_name(:is_admin)
      %th= User.human_attribute_name(:created_at)
      %th= User.human_attribute_name(:updated_at)
      %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to(user.name, [:admin, user])
          %td= user.email
          %td= user.is_admin? ? 'O' : 'X'
          %td= user.created_at
          %td= user.updated_at
          %td
            = link_to('編輯', edit_admin_user_path(user), class: 'btn btn-primary mr-3')
            = link_to('刪除', [:admin, user], method: :delete, data: { confirm: "確定刪除 「#{user.name}」?"}, class: 'btn btn-danger')

app/views/admin/users/new.html.haml
%h1 新增用戶
.nav.justify-content-end
  = link_to('用戶列表', tasks_path, class: 'nav-link')

= render partial: 'form', locals: { task: @task }

app/views/admin/users/show.html.haml
%h1 用戶資訊

.nav.justify-content-end
  = link_to('用戶列表', admin_users_path, class: 'nav-link')
%table.table.table-hover
  %tbody
    %tr
      %th= User.human_attribute_name(:id)
      %td= @user.id
    %tr
      %th= User.human_attribute_name(:name)
      %td= @user.name
    %tr
      %th= User.human_attribute_name(:email)
      %td= @user.email
    %tr
      %th= User.human_attribute_name(:is_admin)
      %td= @user.is_admin? ? 'O' : 'X'
    %tr
      %th= User.human_attribute_name(:created_at)
      %td= @user.created_at
    %tr
      %th= User.human_attribute_name(:updated_at)
      %td= @user.updated_at

= link_to('編輯', edit_admin_user_path(@user), class: 'btn btn-primary mr-3')
= link_to('刪除', [:admin, @user], method: :delete, data: { confirm: "確定刪除 「#{@user.name}」?"}, class: 'btn btn-danger')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TaskManagement
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand TaskManagement
      %ul.navbar.nav.ml-auto
        - if current_user
          %li.nav-item=link_to('任務列表', tasks_path, class: 'nav-link')
          - if current_user.is_admin?
            %li.nav-item=link_to('用戶資訊', admin_user_path(current_user), class: 'nav-link')
          %li.nav-item=link_to('登出', logout_path, method: :delete, class: 'nav-link')
        - else
          %li.nav-item=link_to('登入', login_path, class: 'nav-link')
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice      
      = yield

app/views/tasks/_form.html.haml
= form_with model: task, local: true do |f|
  .form-group
    = f.label :name, '任務名稱'
    = f.text_field :name, class: 'form-control', style: 'width: auto;'
  %br 
  .form-group
    = f.label :description, '任務說明'
    = f.text_area :description, class: 'form-control', style: 'width: auto;'
  %br
  .form-group 
    = f.label :image, '選擇檔案'
    = f.file_field :image, class: 'form-control'
  %br
  = f.submit nil, class: 'btn btn-primary'  

app/views/tasks/_sort_tasks.html.haml
= search_form_for @q, class: 'mt-xs-20' do |f|
  = f.search_field :name_cont, class: 'form-control', placeholder: '依任務名稱查詢'
  %br
  = f.submit nil, class: 'btn btn-primary form-control' 

app/views/tasks/edit.html.haml
%h1 編輯任務
.nav.justify-content-end
  = link_to('任務列表', tasks_path, class: 'nav-link')

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.haml
%h1 任務列表

%br
= link_to('新增任務', new_task_path, class: 'btn btn-primary')
%br 
%br 
= render partial: 'sort_tasks', locals: { q: @q }
%br
.mb-3 
  = paginate(@tasks)
%p   
  = page_entries_info(@tasks)

%table.table.table-hover
  %thead.thead-default
    %tr
      %th= sort_link(@q, :name, '任務名稱', [:name, created_at: :desc])
      %th= Task.human_attribute_name('建立時間')
      %th
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to(task.name, task_path(task))
        %td= task.created_at
        %td
          = link_to(edit_task_path(task), class: 'btn btn-default mr-3')  do
            %i.fa.fa-pencil.fa-fw
          = link_to(task, method: :delete, data: { confirm: "確定刪除 「#{task.name}」?"}, class: 'btn btn-default') do
            %i.fa.fa-trash.fa-fw

= link_to('下載', tasks_path(format: :csv), class: 'btn btn-primary mb-3')

app/views/tasks/new.html.haml
%h1 新增任務
.nav.justify-content-end
  = link_to('任務列表', tasks_path, class: 'nav-link')

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.haml
%h1 任務詳情

.nav.justify-content-end
  = link_to('任務列表', tasks_path, class: 'nav-link')
%table.table.table-hover
  %tbody
    %tr
      %th= Task.human_attribute_name(:id)
      %td= @task.id
    %tr
      %th= Task.human_attribute_name(:name)
      %td= @task.name
    %tr
      %th= Task.human_attribute_name(:description)
      %td= @task.description
    %tr
      %th= Task.human_attribute_name(:created_at)
      %td= @task.created_at
    %tr
      %th= Task.human_attribute_name(:updated_at)
      %td= @task.updated_at  
    %tr 
      %th= Task.human_attribute_name(:image)
      %td= image_tag @task.image.variant(resize: '150x150') if @task.image.attached?
      
= link_to('編輯', edit_task_path, class: 'btn btn-primary mr-3')
= link_to('刪除', @task, method: :delete, data: { confirm: "確定刪除 「#{@task.name}」?"}, class: 'btn btn-danger')